--CRIA O BANCO DE DADOS romanbd
CREATE DATABASE romanbd;

--DEFINE O BANCO DE DADOS QUE SERÁ UTILIZADO
USE romanbd;

--CRIA A TABELA TIPOSUSUARIO COM AS COLUNAS ID E TIPO_USUARIO
CREATE TABLE TIPOSUSUARIO (
    ID INT IDENTITY PRIMARY KEY,
    TIPO_USUARIO VARCHAR(100) UNIQUE NOT NULL
);

--CRIA A TABELA EQUIPES COM AS COLUNAS ID E EQUIPE
CREATE TABLE EQUIPES (
    ID INT IDENTITY PRIMARY KEY,
    EQUIPE VARCHAR(100) UNIQUE NOT NULL
);

--CRIA A TABELA USUARIOS COM AS COLUNAS ID, NOME, EMAIL, SENHA, TIPOUSUARIO_ID E
--EQUIPE_ID
CREATE TABLE USUARIOS (
    ID INT IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    TIPOUSUARIO_ID INT FOREIGN KEY REFERENCES TIPOSUSUARIO(ID) NOT NULL,
    EQUIPE_ID INT FOREIGN KEY REFERENCES EQUIPES(ID)
);

--CRIA A TABELA TEMAS COM AS COLUNAS ID, TEMA E ATIVO
CREATE TABLE TEMAS (
    ID INT IDENTITY PRIMARY KEY,
    TEMA VARCHAR(100) UNIQUE NOT NULL,
    ATIVO BIT DEFAULT(1)
);

CREATE TABLE PROJETOS (
    ID INT IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    TEMA_ID INT FOREIGN KEY REFERENCES TEMAS(ID)
);