CREATE DATABASE romanbd

USE romanbd

CREATE TABLE TIPOSUSUARIO (
    ID INT IDENTITY PRIMARY KEY,
    TIPO_USUARIO VARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE EQUIPES (
    ID INT IDENTITY PRIMARY KEY,
    EQUIPE VARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE USUARIOS (
    ID INT IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    TIPOUSUARIO_ID INT FOREIGN KEY REFERENCES TIPOSUSUARIO(ID),
    EQUIPE_ID INT FOREIGN KEY REFERENCES EQUIPES(ID)
)

CREATE TABLE TEMAS (
    ID INT IDENTITY PRIMARY KEY,
    TEMA VARCHAR(100) UNIQUE NOT NULL,
    ATIVO BIT DEFAULT(1)
)

CREATE TABLE PROJETOS (
    ID INT IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    TEMA_ID INT FOREIGN KEY REFERENCES TEMAS(ID)
)