--DEFINE O BANCO DE DADOS QUE SERÁ UTILIZADO
USE romanbd;

--EXIBINDO OS TIPOS DE USUARIOS
SELECT * FROM TIPOSUSUARIO;

--EXIBINDO TODOS OS USUÁRIOS
SELECT * FROM USUARIOS;

--EXIBINDO TODOS OS PROJETOS
SELECT * FROM PROJETOS;

--EXIBINDO OS TEMAS ATIVOS
SELECT * FROM TEMAS WHERE ATIVO = 1;

--EXIBINDO TODAS AS EQUIPES
SELECT * FROM EQUIPES;